### ISSUE TITLE
Fixing icon sizes on notifications page

### ISSUE THREAD

**Issue by niclashoyer** [OpenMage/OpenMage.github.io#101]
We would like to fix the icon sizes here:

https://www.openmage.org/Web_Notifications/2019/06/24/OpenMage.html

The social icons are huge. I can't find the code for them in the repo here. Any hints? All page templates that include a footer seem to be different.

**Comment by niclashoyer** [comment]
@Flyingmana any hints?

**Comment by Flyingmana** [comment]
fixed it, seems it happened because the web notifications use a different template but the same stylesheet. Did resolve it with a bit of patchwork
