### ISSUE TITLE
Update Front-Commerce logo

### ISSUE THREAD

**Issue by Kagaminara** [OpenMage/OpenMage.github.io#108]
Hello !

Would it possible for you to update [Front-Commerce logo](https://github.com/OpenMage/OpenMage.github.io/blob/master/assets/images/logo/fc-logo.png) on your website please? We changed it a while back and we don't want to confuse users.

Here's the new one :
![image](https://user-images.githubusercontent.com/4162177/185885001-c491ee54-df80-47ae-9cd4-9ecf7d96bc0e.png)

Thank you very much !

_Gaëtan @Front-Commerce_

**Comment by colinmollenhour** [comment]
Hi Gaëtan,

I've updated the logo with the square version from your github page. Let 
me know if you'd prefer the rectangular one, but keep in mind the page 
design currently limits width to just 210px.

Thanks,
Colin

**Comment by Kagaminara** [comment]
Hello,

Yes it's perferctly fine, thank you very much !
