### ISSUE TITLE
Add code to rewrite HTTP to HTTPS

### ISSUE THREAD

**Issue by simbus82** [OpenMage/OpenMage.github.io#28]
http://www.openmage.org/ is not redirected with a 301 to https://www.openmage.org/

This can leads some SEO&Branding problems in this times when OpenMage is seen as the Saint Graal of many Magento Merchants.

It's important to not use a JS redirect, but like for PHP websites some code like that we use in htaccess...
For example:
```
###
# Redirect all non-ssl to ssl.
RewriteCond %{HTTPS} off
RewriteRule ^(.*)$ https://www.openmage.org/$1 [R=301,L]
###
```

**Comment by colinmollenhour** [comment]
I checked "Enforce HTTPS" in the project settings.
