### ISSUE TITLE
Update "Partners" page

### ISSUE THREAD

**Issue by colinmollenhour** [OpenMage/OpenMage.github.io#38]
Please assign to yourself if you are claiming this task.

* organize content into one long-scroll page?
* make this more graphical, like a grid of logos/avatars rather than a table
* call out "Security" partnerships? E.g. Sansec.io, Nexcess, Webscale have all agreed to communicate/collaborate with us on security vulnerabilities

**Comment by sreichel** [comment]
Not sure if im right here ... (sub-page Freelancers )

Is it possible to render url/homepage link different/correctly? (i have no website atm, just an email that is not clickable :()
Where does "# of contributions" comes from? I'm not really in doubt that i have more then 3 contributions :P

**Comment by colinmollenhour** [comment]
The data comes from here: https://github.com/OpenMage/OpenMage.github.io/blob/master/_data/partners/freelancer.json
and it is rendered by the template file here:
https://github.com/OpenMage/OpenMage.github.io/blob/master/partners/freelancer.html

However, I think this needs to be MUCH more automatic as nobody can be expected to take the time to update everyone's contributions. The new homepage has a list of the top contributors and a link to the Github reports which gives a good representation of contributions.

So, I'd be inclined to let the homepage cover the Contributors and then we can remove the contributions data from the Freelancers page and just list those that are generally accepting OpenMage-related work along with contact info, Github username, and an email or website.

**Comment by sreichel** [comment]
Another one ... cone you please add user names to agencies? I'd like to add labels to related PR/issues.

**Comment by adam-maciejewski** [comment]
I'm taking this page to coding based on this project: https://xd.adobe.com/view/d27e9c78-2374-4e5c-4c5c-8cad821abe3c-a44f/

**Comment by Flyingmana** [comment]
Do we actually need an exact/up2date list of contributions?
Everything which is not directly code or interaction here is not easy to validate.
Do we need to know about PRs/Issues beeing related to certain agencies/people? (and if, then we can still automate it instead of handling this manually)


@sreichel you can add an `mailto:` instead of the https://, this should make it a clickable email. Alternatively you could modify the template to handle "no-url, but email" differently.

**Comment by Flyingmana** [comment]
what may be usefull at a later state, to somehow also show the country, I had some questions about people active in certain countries.

**Comment by sreichel** [comment]
I'll update. ro mail to .... and maby make homepage :P

**Comment by colinmollenhour** [comment]
@adam-maciejewski Please incorporate #50 into the design. Looks great!

**Comment by sreichel** [comment]
MageOne has update partner page (since my last visiit) ... https://mage-one.com/mage-one-partners/

Can have more nice view then a table?  (btw ... number of contributens for FA is 3 for all)

Some space to introduce partner, show some logos would be nice ...

With Amasty (anyone here?)  and rack::speed (german hoster) i had contact past years ... i'll try to reach them next days.

**Comment by colinmollenhour** [comment]
Please see the latest mockup:

https://xd.adobe.com/view/ff7f0bde-4255-4cdd-8479-685b04247d36-aa2c/?fullscreen

The homepage contributors tile grid comes straight from the Github API so to some extent I think this replaces the contributions count on the Freelancers page. Completely maintenance-free.

What about changing the urls to link to the commit list instead of the profile page? E.g. https://github.com/OpenMage/magento-lts/commits?author=sreichel instead of https://github.com/sreichel ?

@adam-maciejewski Please make it so that hovering the agency tiles swaps the tile with the description text.

@sreichel What are your thoughts on incorporating freelancers into this page? There is a pretty fine line between freelancers and agencies, maybe they should just be listed similarly, one grid for partners and then another for freelancers?

**Comment by sreichel** [comment]
Nice. Thanks for this work :+1: 

(comment later ....)

**Comment by colinmollenhour** [comment]
The Partners page has been updated with the new design, much more visually appealing! Thanks @adam-maciejewski and your team!

However, the freelancers were not added.. Need to collect some thoughts one how we want to handle these listings. Should there be an additional section for them or should freelancers just be added as agencies or should just the homepage contributors section suffice?

**Comment by Flyingmana** [comment]
I think its important to list them separate, as people usually decide specifically if they want to hire a company, or an individual. (Which is why some people work in a one-person company as agency)

Also, I did not directly recognize the Links as clickable Links, so this could also be an issue for others.

**Comment by adam-maciejewski** [comment]
OK, @colinmollenhour and @Flyingmana so I will add link to https://www.openmage.org/partners/freelancer.html subpage in this place:  

![obraz](https://user-images.githubusercontent.com/66788708/87298079-deb4f480-c509-11ea-8417-538154f08910.png)

If you would like to add any other changes, please let me know.

**Comment by sreichel** [comment]
> I think its important to list them separate, as people usually decide specifically if they want to hire a company, or an individual. (Which is why some people work in a one-person company as agency)

Yep, but they should be listet also at the partners page , just in its own section. Maybe take github-data (img, homepage, email).

> Also, I did not directly recognize the Links as clickable Links, so this could also be an issue for others.

:+1: 

----

General questions:

What makes the differnce between a _"partner"_ or a _"module vendor"_?

Are partners agencies that people that contribute to the code? If yes, is it possible to add some labels for them? Personanally i've no glue who is behind that listet partners ;) And blackfire.io should not be listeted as module vendor, but as partner?

As "webkul" started there could be at least one point of contribution type listed (Bug Reports, ...)

And a _"module vendor"_ is someone who supports OpeneMage with his extensions?

Is it possible to add a new section for agancies that are neither code contributors nor module vendors, like blackfire.io or splendit for documentation hosting?

**Comment by adam-maciejewski** [comment]
Please translate description for two module vendors to DE language (https://www.openmage.org/de/partners/index.html#module-vendors):

![obraz](https://user-images.githubusercontent.com/66788708/95081579-0935d880-071a-11eb-96aa-115015285102.png)

**Comment by adam-maciejewski** [comment]
Page is done so i think that we can close this ticket:
- https://www.openmage.org/partners/index.html
- https://www.openmage.org/de/partners/index.html

**Comment by nickw108** [comment]
I'd like to add my agency, but I'm having problems with `bundle install`, so I'm wondering if I can just add the info to `agency.json` and create a pull request without testing this locally?

**Comment by Flyingmana** [comment]
@nickw108 yes thats fine, we take care of fixing issues afterwards, as its usually just a typo or similar which produces a clear error message.
