### ISSUE TITLE
Update "Modules" page

### ISSUE THREAD

**Issue by colinmollenhour** [OpenMage/OpenMage.github.io#39]
Please assign to yourself if you are claiming this task.

We only have three.. I think it isn't a good look being half-baked so would like to either remove for now or replace with content that requires less maintenance (like links to package repos or other resources).

Ideas?

**Comment by sreichel** [comment]
Please remove/hide for now and lets think about extension we recommand ... (production vs dev?)

modman.... ;)
Firegento_Debug
Aoe_Scheduler
Aoe_AdvancedTemplateHints
... CommitHooks ...
... 

Should these also be add to composer `suggest`?

**Comment by colinmollenhour** [comment]
PRs welcome. :)

My thoughts are to provide a "starter" project that includes the boilerplate extensions and serves as a reference project. Probably put it in a separate repo that a user can easily fork, then just link to it from the Install page and other places.

Additionally, provide some good links to other resources that are effectively alternatives to Magento Connect.

Maintaining a list of extensions on our own site is not something I'm personally interested in and I don't think it it OpenMage's primary value proposition. If anyone disagrees *and* is willing to do the maintenance I wouldn't have any objections, though. :)

**Comment by colinmollenhour** [comment]
@Flyingmana do you have any preferences here?

**Comment by Flyingmana** [comment]
We are able to direct people to pages which list them like

https://github.com/topics/openmage 

There was one marketplace like Website, I forgot which one, but if we can partner with them/link to them, this would sure be of benefit.

We should only in rare exceptions add something to the "suggest" inside composer.json 

The Page should also contain some hints how to promote modules, like adding on github the "openmage" and "openmage-module" topics.
Also to add them to packagist with according keywords used in the composer.json
https://packagist.org/search/?tags=openmage

**Comment by colinmollenhour** [comment]
@Flyingmana Can you provide some content for this in a simple format like Markdown or Word Doc? If you can provide that then we can take over redesigning the page to make it look nice. If you cannot provide that sometime soon I suggest we remove the modules page until it is more complete. Let me know what you prefer.

**Comment by sreichel** [comment]
I think [mageres](https://github.com/aleron75/mageres#extensions) has already listed most important modules .... some may be not maintained anymore, some i did not try, but it seams nearly "complete".

**Comment by sreichel** [comment]
> Can you provide some content for this in a simple format like Markdown or Word Doc?

- https://github.com/aleron75/mageres/issues/76
- https://github.com/aleron75/mageres/blob/master/README-M1.md

Let's go :)

(Maybe check for outdated modules and resources)

**Comment by colinmollenhour** [comment]
That's a great resource! Do we want to take over this project though? I tend to think we are better off keeping it where it is if the maintainers will continue to support it rather than duplicate it or take it over thereby increasing our workload. Or put differently, allow the community to contribute more naturally and effectively by continuing the projects they started themselves.

**Comment by sreichel** [comment]
Preferd ...

- maintainers continue to support
- we encourage people to contribute mageres, link back, ...
- use `resources-m1.csv` (see comment) to generate data for module page

or

- remove this page

**Comment by sreichel** [comment]
(Will be) closed with https://github.com/OpenMage/magento-lts/pull/4349#issuecomment-2495144516
