### ISSUE TITLE
Update "Changelog" page

### ISSUE THREAD

**Issue by colinmollenhour** [OpenMage/OpenMage.github.io#42]
Please assign to yourself if you are claiming this task.

https://www.openmage.org/magento-lts/changelog/magento1-openmage-20_0.html

This is a bear, but very important.. Any help you can offer here would be much appreciated. See discussion here: https://github.com/OpenMage/magento-lts/issues/155

**Comment by sreichel** [comment]
index page needs an update ...

```
Merged Pull Requests
200
```

https://github.com/OpenMage/magento-lts/pulls?q=is%3Apr+is%3Amerged

> 463 Total

**Comment by adam-maciejewski** [comment]
I'm taking this page to coding, based on this project: https://xd.adobe.com/view/c23bf9fc-7aba-46a4-bae9-d1061cab6c4a-9768/

**Comment by adam-maciejewski** [comment]
Page is ready: https://www.openmage.org/magento-lts/changelog/magento1-openmage-20_0.html

@Flyingmana please prepare translations for DE language version: https://www.openmage.org/de/magento-lts/changelog/magento1-openmage-20_0.html
