### ISSUE TITLE
Wrong links in OpenMage Module Fostering

### ISSUE THREAD

**Issue by sreichel** [OpenMage/OpenMage.github.io#46]
Not sure if it belongs here, but README links to https://www.openmage.org/2019/08/18/new-home-magento-connect-modules.html result in 4040 ...

**Comment by sreichel** [comment]
Today i tried to install a few modules, but .... modman is missing so deployment was not possible.

Chances to get these added via some automation?

**Comment by sreichel** [comment]
Prepared 2840 commits  to get told it is not wanted ....

**Comment by colinmollenhour** [comment]
The 404 was fixed a few weeks ago, sorry about that, it got a different URL when we updated the site.

**Comment by sreichel** [comment]
Also added modman files, completed composer.jsons ....

**Comment by sreichel** [comment]
Example:

```
  [ErrorException]                                                                                           
  Unable to find deploy strategy for module: "openmage-module-fostering/zsoltnet_glslabel" no known mapping  
  sourceDir: "/var/www/vhosts/openmage/lts/vendor/openmage-module-fostering/zsoltnet_glslabel"   
```
I'v wrote a script to update all modules. It was done and only needs to be pushed, but I should write code for tooling kit instead.

No. This is wasting my time.
